### ISSUE TITLE
Checklist Práctica Final

### ISSUE THREAD

**Issue by JavierSanzSaez** [JavierSanzSaez/RDSV#1]
# Checklist Práctica final

## Requisitos mínimos

- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [ ] Incluyendo el on-boarding de NS/VNFs y la instanciación de NS mediante línea de comandos

### **Familiarización con el interfaz de configuración de VyOS**
- [x] #21
### **Sustituir la VNF vCPEpor una VNF basada en VyOS**
- [x] #9
- [x] #10
- [x] #11
### **Configuración del routerVyOS**
- [x] #12
- [x] #13
### **Añadir la nueva VNF “arpwatch”**
- [x] #14
- [x] #15
- [x] #16
### **Gestión de QoSen la frontera de la red de acceso, en vclass(y en brgX)**

- [x] #17
- [x] #18
- [x] #19
- [x] #20

## Tareas opcionales

- [ ] Sustituir el switchde brgXpor un conmutador controlado por OpenFlowdesde el Ryu, incluyendo la gestión de la calidad de servicio desde Ryu, controlando el brgX, para limitar el ancho de banda de subida desde la red residencial
- [ ] Soporte IPv6 
- [ ] DHCP para IPv6
